version: '3'


volumes:
  greyfish:
  influxdb:


services:


  greyfish:
    build: .
    image: "greyfish/manager"
    ports:
      - "2443:2443"
    environment:
      - greyfish_key
      - greyfish_threads
      - orchestra_key
      - URL_BASE
      - REDIS_AUTH
      - INFLUXDB
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_READ_USER
      - INFLUXDB_READ_USER_PASSWORD
      - INFLUXDB_WRITE_USER
      - INFLUXDB_WRITE_USER_PASSWORD

    command: "tail -F anything"


  # Define an InfluxDB service
  influxdb:
    image: influxdb:latest
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_READ_USER
      - INFLUXDB_READ_USER_PASSWORD
      - INFLUXDB_WRITE_USER
      - INFLUXDB_WRITE_USER_PASSWORD
    command: "influxd"


  redis:
    image: 'redis:4-alpine'
    environment:
      - REDIS_AUTH
    command: redis-server --requirepass $REDIS_AUTH
    ports:
      - '6379:6379'
